version: '3.9'
services:
  app:
    container_name: pro-skill-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgres://postgres:secret@db:5432/pro-skill-backend
      NODE_ENV: development
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: pro-skill-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pro-skill-backend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
